language: java

addons:
  sonarcloud:
    organization: "jackgoldsworth-github"
    token:
      secure: "QkEm9YB/x06C/yl67CoaMZ2+4pEQl9uymhPAhEMx4N1hWKw1NmerTvdsjpqfOEyn+RuRMS3W6gqHzESO9dP5zszXygQ84D3qxGcScxXKxCbgSo1/MHVv7sZ3FilbTwRmnHaLT4TBzBrpF9wrv24uKJdNcmOWUE0H+CQ7/cD2iGXLc0Zw2a5xIwMpSv2XBfaJCSi1LmzOx75BCwIUstGBHaKrIBhMnRIYcarcVLXPysVaktr1k9oveRwhtCfVM1ha8CNYwjkaGz8yQYXXDZ8qaoDPtpB1gyF7fVCMK4800unD+sMBg4Q0oXsmIFzD42I3+DakZ0H9lIxsI13VeWPtzNIsZgkWSXmLVVzRZTVXlWSiCsShFBonMHOK3h3OcT2oItkTRy2eaXPf5qFwOL9BRn9t3W2lOevbnHkixfXIq9PcRAxQWtESewJ+r3Z4fFqLhvyAbyxDlv1DUGcC85jgmL6CdNv0+cHIj9cIg48codBq4PENJzsdXtV4gvp/dgpW//SlfvXYyrRs2iyIuE56ATlRoNPJ9jpOXFngsHO3tLnaRdctgZ4Os1aWf0wMB8rtBPt8GyUaulEinK55bLFAABJbBsFy6eTjtOkRxca84a2KQGwgP+R0+XeIjeTHbtm1ZAFoGnk7YP682lJNSYfzpsHS5Svj6GNGwqoF0MxiQJ4="

jdk:
  - openjdk8

install:
  - true

script:
  - "./gradlew sonarqube"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'